services:
    postgis:
        image: ghcr.io/iqgeo/docker-postgis/postgis:15-3.5
        container_name: postgis_${PROJ_PREFIX:-wfm-nmtcfi-poc}
        restart: always
        environment:
            PGDATA: /opt/iqgeo/data/pgdata
            POSTGRES_USER: ${DB_USERNAME:-iqgeo}
            POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
        volumes:
            - pgdata-example:/opt/iqgeo/data/pgdata

    iqgeo-worker:
        build:
            context: ./
            dockerfile: dockerfile.tools
            args:
                - PRODUCT_REGISTRY=${PRODUCT_REGISTRY:-harbor.delivery.iqgeo.cloud/releases_}
        image: iqgeo-${PROJ_PREFIX:-wfm-nmtcfi-poc}-tools:latest
        container_name: iqgeo_${PROJ_PREFIX:-wfm-nmtcfi-poc}_worker
        restart: always
        depends_on:
            - postgis
            - redis
        environment:
            PGHOST: ${DB_HOST:-postgis}
            PGPORT: 5432
            PGUSER: ${DB_USERNAME:-iqgeo}
            PGPASSWORD: ${DB_PASSWORD:-password}
            MYW_DB_NAME: ${MYW_DB_NAME:-wfm-nmtcfi-poc}
            MYW_DB_HOST: ${DB_HOST:-postgis}
            MYW_DB_PORT: 5432
            MYW_DB_USERNAME: ${DB_USERNAME:-iqgeo}
            MYW_DB_PASSWORD: ${DB_PASSWORD:-password}
            SQLALCHEMY_URL: postgresql://${DB_USERNAME:-iqgeo}:${DB_PASSWORD:-password}@${DB_HOST:-postgis}:5432/${MYW_DB_NAME:-wfm-nmtcfi-poc}
            RQ_REDIS_URL: ${REDIS_URL:-redis://:password@redis:6379}
            MYW_TASK_WORKERS: ${MYW_TASK_WORKERS:-1}
            MYW_TASK_QUEUES: ${MYW_TASK_QUEUES:-}
            # START CUSTOM SECTION
            COMSOF_OP_TASK_TIMEOUT: ${COMSOF_OP_TASK_TIMEOUT:-86400}
            COMSOF_OP_TASK_QUEUE: ${COMSOF_OP_TASK_QUEUE:-comsof_ops}
            MYW_COMMS_DEV_DB: ${MYW_DB_NAME:-wfm-nmtcfi-poc}
            MYW_COMMS_ARCHIVE_DIR: ${MYW_COMMS_ARCHIVE_DIR:-}
            MYW_COMMS_REMOTE_URL: http://selenium-chrome:4444
            MYW_COMMS_BASE_URL: http://iqgeo
            GOOGLE_MAPS_API_KEY: ${GOOGLE_MAPS_API_KEY:-}
            COMSOF_OIDC_URL: ${COMSOF_OIDC_URL:-https://dev-id.comsof.com}
            COMSOF_OIDC_REALM: ${COMSOF_OIDC_REALM:-test}
            COMSOF_OIDC_CLIENT: ${COMSOF_OIDC_CLIENT:-integration}
    # END CUSTOM SECTION

    iqgeo:
        build:
            context: ./
            dockerfile: dockerfile.appserver
            args:
                - PRODUCT_REGISTRY=${PRODUCT_REGISTRY:-harbor.delivery.iqgeo.cloud/releases_}
        image: iqgeo-${PROJ_PREFIX:-wfm-nmtcfi-poc}-appserver:latest
        container_name: iqgeo_${PROJ_PREFIX:-wfm-nmtcfi-poc}_appserver
        restart: always
        depends_on:
            - postgis
            - keycloak
            - redis
        environment:
            ALLOW_HTTP: 'YES' # only for local testing. do not include in production or exposed environments!
            WSGI_PROCESSES: 2
            WSGI_THREADS: 4
            PGHOST: ${DB_HOST:-postgis}
            PGPORT: 5432
            PGUSER: ${DB_USERNAME:-iqgeo}
            PGPASSWORD: ${DB_PASSWORD:-password}
            MYW_DB_NAME: ${MYW_DB_NAME:-wfm-nmtcfi-poc}
            MYW_DB_HOST: ${DB_HOST:-postgis}
            MYW_DB_PORT: 5432
            MYW_DB_USERNAME: ${DB_USERNAME:-iqgeo}
            MYW_DB_PASSWORD: ${DB_PASSWORD:-password}
            BEAKER_SESSION_TYPE: ${BEAKER_SESSION_TYPE:-ext:redis}
            BEAKER_SESSION_URL: ${BEAKER_SESSION_URL:-redis://:password@redis:6379/0}
            RQ_REDIS_URL: ${BEAKER_SESSION_URL:-redis://:password@redis:6379/0}
            IQGEO_HOST: ${IQGEO_HOST:-localhost}
            KEYCLOAK_URL: ${KC_PROTOCOL:-http://}${KEYCLOAK_HOST:-keycloak.local}:${KEYCLOAK_PORT:-8080}
            MYW_EXT_BASE_URL: http://${IQGEO_HOST:-localhost} # for access from other devices (e.g. iPad running anywhere)
            # START CUSTOM SECTION
            COMSOF_OP_TASK_TIMEOUT: ${COMSOF_OP_TASK_TIMEOUT:-86400}
            COMSOF_OP_TASK_QUEUE: ${COMSOF_OP_TASK_QUEUE:-comsof_ops}
            MYW_COMMS_DEV_DB: ${MYW_DB_NAME:-wfm-nmtcfi-poc}
            MYW_COMMS_ARCHIVE_DIR: ${MYW_COMMS_ARCHIVE_DIR:-}
            MYW_COMMS_REMOTE_URL: http://selenium-chrome:4444
            MYW_COMMS_BASE_URL: http://iqgeo
            APACHE_TIMEOUT: ${APACHE_TIMEOUT:-1800}
            GOOGLE_MAPS_API_KEY: ${GOOGLE_MAPS_API_KEY:-}
            COMSOF_OIDC_URL: ${COMSOF_OIDC_URL:-https://dev-id.comsof.com}
            COMSOF_OIDC_REALM: ${COMSOF_OIDC_REALM:-test}
            COMSOF_OIDC_CLIENT: ${COMSOF_OIDC_CLIENT:-integration}
        # END CUSTOM SECTION
        ports:
            - ${APPSERVER_PORT:-80}:8080

    keycloak:
        container_name: keycloak_${PROJ_PREFIX:-wfm-nmtcfi-poc}
        image: ghcr.io/iqgeo/utils-keycloak-iqgeo/keycloak:latest
        restart: always
        command: start-dev --import-realm
        environment:
            KC_HOSTNAME: ${KEYCLOAK_HOST:-keycloak.local}
            KC_HOSTNAME_PORT: ${KEYCLOAK_PORT:-8080}
            KC_HTTP_PORT: ${KEYCLOAK_PORT:-8080}
            KEYCLOAK_ADMIN: admin
            KEYCLOAK_ADMIN_PASSWORD: _mywWorld_
            KC_PROXY: edge
            SSL_REQUIRED: none
            IQGEO_DOMAIN: http://${SERVER_NAME-localhost}:${APPSERVER_PORT:-80}
            IQGEO_CLIENT_SECRET: qpyu1mCm8zvvKTXRnKxwap1A6xMChuY6
        ports:
            - ${KC_HTTPS_PORT:-8443}:${KC_HTTPS_PORT:-8443}
            - ${KEYCLOAK_PORT:-8080}:${KEYCLOAK_PORT:-8080}
        networks:
            default:
                aliases:
                    - keycloak.local

    redis:
        container_name: redis_${PROJ_PREFIX:-wfm-nmtcfi-poc}
        image: redis:latest
        restart: always
        command: redis-server --requirepass ${REDIS_PASSWORD:-password}
# START CUSTOM SECTION
# END CUSTOM SECTION

volumes:
    pgdata-example:
        name: ${PROJ_PREFIX:-wfm-nmtcfi-poc}_pgdata-example15
        # START CUSTOM SECTION
        # END CUSTOM SECTION
