services:
    postgis:
        image: ghcr.io/iqgeo/utils-docker-postgis/postgis:12-3.4
        container_name: postgis_${PROJ_PREFIX:-myproj}
        restart: always
        environment:
            PGDATA: /opt/iqgeo/data/pgdata
            POSTGRES_USER: ${DB_USERNAME:-iqgeo}
            POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
        volumes:
            - pgdata-example:/opt/iqgeo/data/pgdata

    iqgeo:
        build:
            context: ./
            dockerfile: dockerfile.appserver
            args:
                - CONTAINER_REGISTRY=${CONTAINER_REGISTRY:-harbor.delivery.iqgeo.cloud/releases/}
        image: iqgeo-myproj-appserver:latest
        container_name: iqgeo_${PROJ_PREFIX:-myproj}_appserver
        restart: always
        depends_on:
            - postgis
            - keycloak
        environment:
            ALLOW_HTTP: 'YES' # only for local testing. do not include in production or exposed environments!
            WSGI_PROCESSES: 2
            WSGI_THREADS: 4
            PGHOST: ${DB_HOST:-postgis}
            PGPORT: 5432
            PGUSER: ${DB_USERNAME:-iqgeo}
            PGPASSWORD: ${DB_PASSWORD:-password}
            MYW_DB_NAME: ${MYW_DB_NAME:-myproj}
            MYW_DB_HOST: ${DB_HOST:-postgis}
            MYW_DB_PORT: 5432
            MYW_DB_USERNAME: ${DB_USERNAME:-iqgeo}
            MYW_DB_PASSWORD: ${DB_PASSWORD:-password}
            BEAKER_SESSION_TYPE: ${BEAKER_SESSION_TYPE:-ext:memcached}
            BEAKER_SESSION_URL: ${BEAKER_SESSION_URL:-memcached:11211}
            IQGEO_HOST: ${IQGEO_HOST:-localhost}
            KEYCLOAK_URL: ${KC_PROTOCOL:-http://}${KC_HOST:-keycloak}:${KEYCLOAK_PORT:-8080}
            MYW_EXT_BASE_URL: http://${IQGEO_HOST:-localhost} # for access from other devices (e.g. iPad running anywhere)
            # START CUSTOM SECTION
            # END CUSTOM SECTION
        ports:
            - ${APPSERVER_PORT:-80}:8080

    keycloak:
        container_name: keycloak_${PROJ_PREFIX:-myproj}
        image: ghcr.io/iqgeo/utils-keycloak-iqgeo/keycloak:latest
        restart: always
        command: start-dev --import-realm
        environment:
            KC_HOSTNAME: keycloak
            KC_HOSTNAME_PORT: ${KEYCLOAK_PORT:-8080}
            KC_HTTP_PORT: ${KEYCLOAK_PORT:-8080}
            KEYCLOAK_ADMIN: admin
            KEYCLOAK_ADMIN_PASSWORD: _mywWorld_
            KC_PROXY: edge
            IQGEO_DOMAIN: http://${SERVER_NAME-localhost}:${APPSERVER_PORT:-80}
            IQGEO_CLIENT_SECRET: qpyu1mCm8zvvKTXRnKxwap1A6xMChuY6
        ports:
            - ${KC_HTTPS_PORT:-8443}:${KC_HTTPS_PORT:-8443}
            - ${KEYCLOAK_PORT:-8080}:${KEYCLOAK_PORT:-8080}

    memcached:
        container_name: memcached_${PROJ_PREFIX:-myproj}
        image: memcached:latest
        restart: always
    # START CUSTOM SECTION
    # END CUSTOM SECTION

volumes:
    pgdata-example:
        # START CUSTOM SECTION
        # END CUSTOM SECTION
